version: "3"
services:
  app:
    image: webauthn
    build: .
    container_name: webauthn
    ports:
      - 8000:8000
    volumes:
      - ../webauthn:/app/webauthn
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: 300m
  postgres:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webauthn
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
